### ISSUE TITLE
Unknown options that previously used to work

### ISSUE THREAD

**Issue by ZzZombo** [copperwater/xNetHack#210] opened 2024-04-20 02:11 UTC
`roguesymset` and `clicklook` no longer are accepted by the game.

**Comment by copperwater** [comment] 2024-04-20 11:30
roguesymset has been gone since 2021 because there's no longer a rogue level to use it on. Simply remove it from your configs.

I never touched clicklook; it looks like the syntax of this has changed upstream. You would now use `BIND=mouse1:clicklook` or `BIND=mouse2:clicklook` instead. I confirmed that those are accepted by xNetHack whereas a simple boolean clicklook isn't.

**Comment by copperwater** [comment] 2024-04-21 20:05
Closing because the options not being recognized in the current version of xNetHack works as expected.

**Closed as not planned by copperwater** 2024-04-21 20:05 UTC
