### ISSUE TITLE
Gehennom level with no maze

### ISSUE THREAD

**Issue by Ardub23** [copperwater/xNetHack#56] opened 2021-10-31 23:23 UTC
A filler level in Gehennom generated with no maze, only solid rock and a few rooms.
![2021-10-31 16_58_24-hardfought org - PuTTY](https://user-images.githubusercontent.com/48235540/139604347-c464c55f-86fb-40e3-84e1-7ad1656dbc7f.png)

I've occasionally seen a single room fail to connect properly with the maze, requiring me to dig in or out, but this is the first time I've seen no maze at all. I used a stethoscope to search for secret passages all around the room with the upstair, then dug a few tiles to the right before reading a mapping scroll.

My best guess as to the cause is that the tiny room in the lower-left was supposed to be the maze, but somehow it stopped generating past a few tiles. That guess is based on that it's too small to be a normal room, but it could be a short piece of maze hallway.

**Comment by entrez** [comment] 2021-11-09 23:03
Very interesting... I was just able to reproduce it.  Similar setup where the mazewalk starts wedged between a room and the edge of the map.  Pretty sure I understand what is going on here now.

<img width="410" alt="Screen Shot 2021-11-09 at 5 23 46 PM" src="https://user-images.githubusercontent.com/40038830/141015356-56ae11c5-ed96-4bff-aaef-2f1c5159b368.png">

**Comment by entrez** [comment] 2021-11-09 23:27
I hate how referencing an issue makes my obsessive force-pushing even more obvious

**Comment by copperwater** [comment] 2021-12-02 22:34
While fixes to maze+rooms bugs like entrez's are appreciated, I am not planning on personally putting any effort into fixing them since the plan is to give Gehennom a substantial overhaul that doesn't involve mazes (planned for version 8.0 currently; upcoming version is 7.0.)

That said, if there's a PR that fixes this, I'll merge it.

**Comment by copperwater** [comment] 2022-02-16 00:41
Fixed on the 7.0-savebreaking branch. It will not be fixed in 6.3.

**Closed as completed by copperwater** 2022-02-16 00:41 UTC
